version: '2.1'
services:
  # plex:
  #   image: linuxserver/plex:latest
  #   container_name: plex
  #   environment:
  #     - PUID=501
  #     - PGID=20
  #     - VERSION=docker
  #   volumes:
  #     - ~/docker-services/plex/config:/config
  #     - ~/content:/mnt
  #   ports:
  #     - 32400:32400
  #   restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      # - PUID=501
      # - PGID=20
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:                
      - ~/docker-services/transmission/config:/config
      - ~/content/media/torrents:/mnt/media/torrents
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      # - PUID=501
      # - PGID=20
      - TZ=Europe/London
      - RUN_OPTS=run options here #optional
    volumes:
      - ~/docker-services/jackett/config:/config
      - ~/content/media/torrents/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      # - PUID=501
      # - PGID=20
      - TZ=PST
      - UMASK_SET=022 #optional
    volumes:
      - ~/docker-services/sonarr/config:/config
      - ~/content/media:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      # - PUID=501
      # - PGID=20
      - TZ=PST
    volumes:
      - ~/docker-services/radarr/config:/config
      - ~/content/media:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped

  # ombi:
  #   image: linuxserver/ombi
  #   container_name: ombi
  #   environment:
  #     # - PUID=501
  #     # - PGID=20
  #     - TZ=PST
  #     - BASE_URL=/ombi #optional
  #   volumes:
  #     - ~/docker-services/ombi/config:/config
  #   ports:
  #     - 3579:3579
  #   restart: unless-stopped
