version: "3.6"
services:
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./docker-services/organizr/config:/config
    environment:
      - TZ=Europe/London
