version: "3.6"
services:
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./docker-services/organizr/config:/config
    environment:
      - TZ=Europe/London

  monitorr:
    container_name: monitorr
    hostname: monitorr
    image: monitorr/monitorr:latest
    restart: unless-stopped
    ports:
      - 9001:80
    volumes:
      - ./docker-services/monitorr/app:/app
    environment:
      - TZ=Europe/London
