version: "3.6"

volumes:
  code:

services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-server
    restart: unless-stopped    
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TZ: "Europe/London"
      VERSION: "1.18.2"
      TYPE: "VANILLA"
      MEMORY: "2G"
    tty: true
    stdin_open: true
    volumes:
      - code:/data
      # - ./docker-services/minecraft/data:/data:cached

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "./docker-services/minecraft/data"
      beta: "volume://code"
      mode: "two-way-resolved"
      ignore:
        paths:
          - libraries
          - logs
          - versions