version: "3.6"
services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-server
    restart: unless-stopped    
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TZ: "Europe/London"
      VERSION: "1.18.2"
      TYPE: "VANILLA"
      MEMORY: "2G"
    # tty: true
    # stdin_open: true
    volumes:
      - ./docker-services/minecraft/data:/data:cached

